name: PlayerFNGTransaction
version: '1.0-SNAPSHOT'
main: org.fng.playerFNGTransaction.PlayerFNGTransaction
api-version: '1.21'
commands:
  solde:
    description: Affiche le solde du joueur
    usage: /solde
    permission: fng.solde
  transaction:
    description: Faire une transaction à un joueur
    usage: /transaction <joueur> <quantité>
    permission: fng.transaction
  accepte:
    description: Accepter une transaction
    usage: /accepte
    permission: fng.accepte